
//	portal用ワークスペース。データフォルダに書かれる。

local wspath = skGetCurrentDir() .. "/.portal.ws";

workspace <- null;
try{
	local wsfile = FileRef( wspath);
	if( wsfile.exists()){
		local bb = wsfile.load();
		if( bb) workspace = decodeJSON( bb);
	}
}catch( ex){
	printexception( ex);
}

if( workspace){
	workspace.name <- sakana["appname"] || "unknown";
}else{
	workspace = {
		name = sakana["appname"] || "unknown",
		projlist = [],
		asseturls = [],
		lasttmpl = null,	//	最後に選択したテンプレート
		tooltags = null,
		lang = null,
		uiscale = 100,
		tabsync = true,
		showconsole = false,
		autochk = 24*60*60,		//	1日1回
		showhome = true,
		projsort = "name",
		favofirst = true,
	}
}

//
//	functions
//
function saveWorkspace(){
	local wsfile = FileRef( wspath);
	local bb = ByteBuffer();
	bb.putText( encodeJSON( workspace, 1|4));
	bb.pos = 0;
	wsfile.save( bb);
}
